---
# tasks file for spacemacs



# git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

- name: install git 
  become: yes
  apt:
    name: git-core
    update_cache: yes
    state: present 

- name: install emacs 
  become: yes
  apt: 
    name: emacs
    update_cache: yes
    state: present

- name: install spacemacs 
  git:
    repo: "https://github.com/syl20bnr/spacemacs"
    dest: "/home/{{ ansible_ssh_user }}/.emacs.d"
    clone: yes
    force: yes
    accept_hostkey: yes
  become: yes
  become_user: "{{ansible_ssh_user}}" 
 
- name: make spacemacs config file
  template: 
    src: spacemacs.config.ab 
    dest: '/home/{{ ansible_ssh_user }}/.spacemacs' 
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}' 
    mode: 0640

- name: start emacs server if not present
  blockinfile:
    dest: '/home/{{ ansible_ssh_user }}/.bashrc'
    insertbefore: "#THIS MUST BE "    
    block: |
      export ALTERNATE_EDITOR=""
      alias e='emacsclient -t'
    marker:"# {mark} ANSIBLE MANAGED BLOCK {{item.name}}"

  
