;; -*- mode: emacs-lisp -*-
;; This file is loaded by Spacemacs at startup.
;; It must be stored in your home directory.

(defun dotspacemacs/layers ()
  "Configuration Layers declaration.
You should not put any user code in this function besides modifying the variable
values."
  (setq-default
   ;; Base distribution to use. This is a layer contained in the directory
   ;; `+distribution'. For now available distributions are `spacemacs-base'
   ;; or `spacemacs'. (default 'spacemacs)
   dotspacemacs-distribution 'spacemacs
   ;; List of additional paths where to look for configuration layers.
   ;; Paths must have a trailing slash (i.e. `~/.mycontribs/')
   dotspacemacs-configuration-layer-path '(
   )
   ;; List of configuration layers to load. If it is the symbol `all' instead
   ;; of a list then all discovered layers will be installed.
   dotspacemacs-configuration-layers
   '(
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     ;; auto-completion
     (auto-completion
       :variables
       auto-completion-return-key-behavior 'complete
       auto-completion-tab-key-behavior 'cycle
       :disabled-for org erc)
     cygwin
     ;;better-defaults 
     emacs-lisp
     eyebrowse
     ;;git
     github
     html
     (ibuffer :variables ibuffer-group-buffers-by nil)
     java
     markdown
     outlook
     org
     ;;org-ab
     osx
     pandoc
     ranger
     restclient
     semantic
     (shell :variables shell-default-shell 'eshell)
     (syntax-checking :variables syntax-checking-enable-by-default nil)
     smex
     yaml
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     ;; spell-checking
     ;; syntax-checking
     ;; version-control
     )
   ;; List of additional packages that will be installed without being
   ;; wrapped in a layer. If you need some configuration for these
   ;; packages then consider to create a layer, you can also put the
   ;; configuration in `dotspacemacs/config'.
   dotspacemacs-additional-packages
   '(
     tidy
     helm-bibtex
     ebib
     )
   ;; A list of packages and/or extensions that will not be install and loaded.
   dotspacemacs-excluded-packages '()
   ;; If non-nil spacemacs will delete any orphan packages, i.e. packages that
   ;; are declared in a layer which is not a member of
   ;; the list `dotspacemacs-configuration-layers'. (default t)
   dotspacemacs-delete-orphan-packages t))

(defun dotspacemacs/init ()
  "Initialization function.
This function is called at the very startup of Spacemacs initialization
before layers configuration.
You should not put any user code in there besides modifying the variable
values."
  ;; This setq-default sexp is an exhaustive list of all the supported
  ;; spacemacs settings.
  (setq-default
   ;; One of `vim', `emacs' or `hybrid'. Evil is always enabled but if the
   ;; variable is `emacs' then the `holy-mode' is enabled at startup. `hybrid'
   ;; uses emacs key bindings for vim's insert mode, but otherwise leaves evil
   ;; unchanged. (default 'vim)
   dotspacemacs-editing-style 'emacs
   ;; If non nil output loading progress in `*Messages*' buffer. (default nil)
   dotspacemacs-verbose-loading nil
   ;; Specify the startup banner. Default value is `official', it displays
   ;; the official spacemacs logo. An integer value is the index of text
   ;; banner, `random' chooses a random text banner in `core/banners'
   ;; directory. A string value must be a path to an image format supported
   ;; by your Emacs build.
   ;; If the value is nil then no banner is displayed. (default 'official)
   dotspacemacs-startup-banner nil
   ;; List of items to show in the startup buffer. If nil it is disabled.
   ;; Possible values are: `recents' `bookmarks' `projects'.
   ;; (default '(recents projects))
   dotspacemacs-startup-lists '(recents bookmarks projects)
   ;; List of themes, the first of the list is loaded when spacemacs starts.
   ;; Press <SPC> T n to cycle to the next theme in the list (works great
   ;; with 2 themes variants, one dark and one light)
   dotspacemacs-themes '(monokai
                         spacemacs-dark
                         spacemacs-light
                         solarized-light
                         solarized-dark
                         leuven
                         zenburn)
   ;; If non nil the cursor color matches the state color.
   dotspacemacs-colorize-cursor-according-to-state t
   ;; Default font. `powerline-scale' allows to quickly tweak the mode-line
   ;; size to make separators look not too crappy.
   dotspacemacs-default-font '("Source Code Pro"
                               :size 14
                               :weight normal
                               :width normal
                               :powerline-scale 1.1)
   ;; The leader key
   dotspacemacs-leader-key "SPC"
   ;; The leader key accessible in `emacs state' and `insert state'
   ;; (default "M-m")
   dotspacemacs-emacs-leader-key "M-SPC"
   ;; Major mode leader key is a shortcut key which is the equivalent of
   ;; pressing `<leader> m`. Set it to `nil` to disable it. (default ",")
   dotspacemacs-major-mode-leader-key ","
   ;; Major mode leader key accessible in `emacs state' and `insert state'.
   ;; (default "C-M-m)
   dotspacemacs-major-mode-emacs-leader-key "C-M-m"
   ;; The command key used for Evil commands (ex-commands) and
   ;; Emacs commands (M-x).
   ;; By default the command key is `:' so ex-commands are executed like in Vim
   ;; with `:' and Emacs commands are executed with `<leader> :'.
   dotspacemacs-command-key ":"
   ;; If non nil `Y' is remapped to `y$'. (default t)
   dotspacemacs-remap-Y-to-y$ t
   ;; Location where to auto-save files. Possible values are `original' to
   ;; auto-save the file in-place, `cache' to auto-save the file to another
   ;; file stored in the cache directory and `nil' to disable auto-saving.
   ;; (default 'cache)
   dotspacemacs-auto-save-file-location 'cache
   ;; If non nil then `ido' replaces `helm' for some commands. For now only
   ;; `find-files' (SPC f f), `find-spacemacs-file' (SPC f e s), and
   ;; `find-contrib-file' (SPC f e c) are replaced. (default nil)
   dotspacemacs-use-ido nil
   ;; If non nil, `helm' will try to miminimize the space it uses. (default nil)
   dotspacemacs-helm-resize nil
   ;; if non nil, the helm header is hidden when there is only one source.
   ;; (default nil)
   dotspacemacs-helm-no-header nil
   ;; define the position to display `helm', options are `bottom', `top',
   ;; `left', or `right'. (default 'bottom)
   dotspacemacs-helm-position 'bottom
   ;; If non nil the paste micro-state is enabled. When enabled pressing `p`
   ;; several times cycle between the kill ring content. (default nil)
   dotspacemacs-enable-paste-micro-state nil
   ;; Which-key delay in seconds. The which-key buffer is the popup listing
   ;; the commands bound to the current keystroke sequence. (default 0.4)
   dotspacemacs-which-key-delay 0.4
   ;; Which-key frame position. Possible values are `right', `bottom' and
   ;; `right-then-bottom'. right-then-bottom tries to display the frame to the
   ;; right; if there is insufficient space it displays it at the bottom.
   ;; (default 'bottom)
   dotspacemacs-which-key-position 'bottom
   ;; If non nil a progress bar is displayed when spacemacs is loading. This
   ;; may increase the boot time on some systems and emacs builds, set it to
   ;; nil to boost the loading time. (default t)
   dotspacemacs-loading-progress-bar t
   ;; If non nil the frame is fullscreen when Emacs starts up. (default nil)
   ;; (Emacs 24.4+ only)
   dotspacemacs-fullscreen-at-startup nil
   ;; If non nil `spacemacs/toggle-fullscreen' will not use native fullscreen.
   ;; Use to disable fullscreen animations in OSX. (default nil)
   dotspacemacs-fullscreen-use-non-native nil
   ;; If non nil the frame is maximized when Emacs starts up.
   ;; Takes effect only if `dotspacemacs-fullscreen-at-startup' is nil.
   ;; (default nil) (Emacs 24.4+ only)
   dotspacemacs-maximized-at-startup nil
   ;; A value from the range (0..100), in increasing opacity, which describes
   ;; the transparency level of a frame when it's active or selected.
   ;; Transparency can be toggled through `toggle-transparency'. (default 90)
   dotspacemacs-active-transparency 90
   ;; A value from the range (0..100), in increasing opacity, which describes
   ;; the transparency level of a frame when it's inactive or deselected.
   ;; Transparency can be toggled through `toggle-transparency'. (default 90)
   dotspacemacs-inactive-transparency 90
   ;; If non nil unicode symbols are displayed in the mode line. (default t)
   dotspacemacs-mode-line-unicode-symbols nil
   ;; If non nil smooth scrolling (native-scrolling) is enabled. Smooth
   ;; scrolling overrides the default behavior of Emacs which recenters the
   ;; point when it reaches the top or bottom of the screen. (default t)
   dotspacemacs-smooth-scrolling t
   ;; If non-nil smartparens-strict-mode will be enabled in programming modes.
   ;; (default nil)
   dotspacemacs-smartparens-strict-mode nil
   ;; Select a scope to highlight delimiters. Possible values are `any',
   ;; `current', `all' or `nil'. Default is `all' (highlight any scope and
   ;; emphasis the current one). (default 'all)
   dotspacemacs-highlight-delimiters 'all
   ;; If non nil advises quit functions to keep server open when quitting.
   ;; (default nil)
   dotspacemacs-persistent-server nil
   ;; List of search tool executable names. Spacemacs uses the first installed
   ;; tool of the list. Supported tools are `ag', `pt', `ack' and `grep'.
   ;; (default '("ag" "pt" "ack" "grep"))
   dotspacemacs-search-tools '("ag" "pt" "ack" "grep")
   ;; The default package repository used if no explicit repository has been
   ;; specified with an installed package.
   ;; Not used for now. (default nil)
   dotspacemacs-default-package-repository nil
   ))

(defun dotspacemacs/user-init ()
  "Initialization function for user code.
It is called immediately after `dotspacemacs/init'.  You are free to put any
user code."
  (server-start)
  (setq-default 
   ;; Evil
   evil-shift-round nil

   ;; Whitespace mode
   whitespace-style '(face tabs tab-mark newline-mark)
   whitespace-display-mappings
   '((newline-mark 10 [172 10])
     (tab-mark 9 [9655 9]))

   ;; Avy
   avy-all-windows 'all-frames

   ;; Ranger
   ranger-override-dired t

   ;; bibtex integration 
   bibtex-completion-bibliography '("~/TODO/library.bib")
   )


  ;; just open the agenda and hide any other windows
  ;; just as function call in startup command
  ;; i.e runemacs.exe --funcall open-org-agenda
  (defun open-org-agenda()
    (org-agenda-list)
    (delete-other-windows)
    )

  )

(defun dotspacemacs/user-config ()
  "Configuration function for user code.
 This function is called at the very end of Spacemacs initialization after
layers configuration. You are free to put any user code."

  ;; Utility functions
  (defun bb/define-key (keymap &rest bindings)
    (declare (indent 1))
    (while bindings
      (define-key keymap (pop bindings) (pop bindings))))

  (defmacro bb/remove-from-list (list-var element)
    `(setq ,list-var (remove ,element ,list-var)))


  ;; move lines up and down using the meta key..
  ;; see http://www.emacswiki.org/emacs/MoveLine
  (defun move-line-up ()
    (interactive)
    (transpose-lines 1)
    (forward-line -2))

  (defun move-line-down ()
    (interactive)
    (forward-line 1)
    (transpose-lines 1)
    (forward-line -1))

  (global-set-key (kbd "M-<up>") 'move-line-up)
  (global-set-key (kbd "M-<down>") 'move-line-down)
;;  (global-set-key (kbd "C-; o s") 'just-one-space)


  ;; Settings
  (setq-default
   tab-width 8
   evil-shift-width 4)

   ;; Keybindings
   (bb/define-key evil-normal-state-map
                  (kbd ";") 'helm-M-x
                  "+" 'spacemacs/evil-numbers-increase
                  "_" 'spacemacs/evil-numbers-decrease
                  "\\" 'evil-repeat-find-char-reverse
                  "[s" (lambda (n) (interactive "p") (dotimes (c n nil) (insert " ")))
                  "]s" (lambda (n) (interactive "p")
                         (forward-char) (dotimes (c n nil) (insert " ")) (backward-char (1+ n))))


   ;; Miscellaneous
   (add-hook 'text-mode-hook 'auto-fill-mode)
   (add-hook 'dired-mode-hook 'deer)

   ;; Some fixes for comint-style buffers
   (dolist (mode '(erc-mode
                   comint-mode
                   term-mode
                   eshell-mode
                   inferior-emacs-lisp-mode))
     (bb/remove-from-list evil-insert-state-modes mode))

   (let ((comint-hooks '(eshell-mode-hook
                         term-mode-hook
                         erc-mode-hook
                         messages-buffer-mode-hook
                         comint-mode-hook)))
     (spacemacs/add-to-hooks (defun bb/no-hl-line-mode ()
                               (setq-local global-hl-line-mode nil))
                             comint-hooks))
   (add-hook 'inferior-emacs-lisp-mode-hook 'smartparens-mode)




   ;; package imports for all packages
   ;; used in the ab-org layer functions
   ;; if these are missing, the wrong version of
   ;; org is imported (e.g. the builtin org version)
   (use-package org-habit)
   (use-package org-agenda)
   (use-package org-id)

   ;; org-mode worg packages (need to be activated here..)
   (use-package org-protocol)
   (use-package org-collector)


   (use-package ob-plantuml)


   ;; integrate cygwin bash shell on windows
   ;; see https://www.emacswiki.org/emacs/NTEmacsWithCygwin
;;   (let* ((cygwin-bin (concat cygwin-root-directory "/bin")))
;;     (when (and (eq 'windows-nt system-type)
;;                (file-readable-p cygwin-root-directory))
       ;; integrate cygwin find instead of windows find (see http://stackoverflow.com/questions/3918341/find-parameter-format-not-correct)
;;       (setq find-program (cons cygwin-bin "/find.exe" ))
;;       (setq find-program (cons cygwin-bin "/grep.exe" ))
;;   )


   ;; integrate ebib into orgmode
   (org-add-link-type "ebib" 'ebib-open-org-link)


)
;; Do not write anything past this comment. This is where Emacs will
;; auto-generate custom variable definitions.
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(aquamacs-additional-fontsets nil t)
 '(aquamacs-customization-version-id 307 t)
 '(aquamacs-tool-bar-user-customization nil t)
 '(browse-url-browser-function (quote browse-url-default-windows-browser))
 '(cua-mode t nil (cua-base))
 '(current-language-environment "UTF-8")
 '(cygwin-mount-cygwin-bin-directory "C:\\bin\\cygwin\\bin")
 '(cygwin-root-directory "C:/bin/cygwin")
 '(ebib-autogenerate-keys t)
 '(ebib-preload-bib-files (quote ("~/TODO/library.bib")))
 '(emulate-mac-german-keyboard-mode t)
 '(global-linum-mode t)
 '(gud-gdb-command-name "gdb --annotate=1")
 '(large-file-warning-threshold nil)
 '(ns-tool-bar-display-mode (quote both) t)
 '(ns-tool-bar-size-mode (quote regular) t)
 '(org-agenda-clockreport-parameter-plist (quote (:link t :maxlevel 3 :narrow 40!)))
 '(org-agenda-cmp-user-defined (quote bh/agenda-sort))
 '(org-agenda-compact-blocks t)
 '(org-agenda-dim-blocked-tasks nil)
 '(org-agenda-files (quote ("~/TODO/" "~/.ews-orgmode/outlook.org")))
 '(org-agenda-sorting-strategy
   (quote
    ((agenda habit-down time-up user-defined-up effort-up category-keep)
     (todo category-up effort-up)
     (tags category-up effort-up)
     (search category-up))))
 '(org-agenda-span 1)
 '(org-agenda-start-with-clockreport-mode t)
 '(org-agenda-sticky t)
 '(org-agenda-tags-column -102)
 '(org-attach-store-link-p t)
 '(org-capture-templates
   (quote
    (("f" "new org file" plain
      (file "~/TODO/refile.org")
      "* %?NEW FILE
#+FILETAGS: %^{filename} 
** meetings
** tasks
** references
** notes")
     ("t" "Todo (not today)" entry
      (file "~/TODO/refile.org")
      "* TODO [#A] %?
 SCHEDULED: %^t 
  %i
" :clock-in t :clock-resume t)
     ("n" "Notes" entry
      (file "~/TODO/refile.org")
      "* %^{TOPIC} 
%?  %i
 ")
     ("j" "Jira issue" entry
      (file "~/TODO/refile.org")
      "*  %^{issue-header} 
** description:
%i%?
** affects version: 

** steps to reproduce: 

** Expected result: 

** Actual result: 

** Components:")
     ("b" "Templates for meeting minutes")
     ("bd" "besprechungsprotokoll" entry
      (file "~/TODO/refile.org")
      "*  %^{thema} 
** Zeit:
%U
** Ort:

** teilnehmer:
*** %?
** agenda: 
%i
** Action items: 
*** TODO 
** Notizen: 
***")
     ("be" "meeting minutes" entry
      (file "~/TODO/refile.org")
      "*  %^{topic} 
** Time:
%U
** Location:

** Participants:
*** %?
** Agenda: 
%i
** Action items: 
*** TODO 
** Notes: 
***")
     ("u" "Unplanned" entry
      (file "~/TODO/unplanned.org")
      "** TODO %? 
   SCHEDULED: %T
 %i 
" :clock-in t :clock-resume t)
     ("o" "Orga" entry
      (file+headline "~/TODO/orga.org" "Orga allgemein")
      "** TODO %? 
   SCHEDULED: %T
 %i 
")
     ("s" "Ideas (someday)" entry
      (file "~/TODO/refile.org")
      "* TODO %^{Title}
  ")
     ("m" "Meeting" entry
      (file "~/TODO/refile.org")
      "* MEETING with %? :MEETING:
%U" :clock-in t :clock-resume t)
     ("p" "Phone call" entry
      (file "~/TODO/refile.org")
      "* PHONE %? :PHONE:
%U" :clock-in t :clock-resume t)
     ("h" "Habit" entry
      (file+headline "~/TODO/habit.org" "Tasks")
      (function my/habit-template))
     ("x" "outlook items" entry
      (file "~/TODO/refile.org")
      "* TODO [#A] %:annotation  :OUTLOOK:
" :immediate-finish t))))
 '(org-clock-into-drawer "LOGBOOK")
 '(org-clock-rounding-minutes 1)
 '(org-columns-default-format
   "%TODO %40ITEM %17Effort(Estimated Effort){:} %SCHEDULED %20CLOCKSUM(Actuals)")
 '(org-completion-use-ido nil)
 '(org-export-backends
   (quote
    (ascii beamer html icalendar latex md odt confluence)))
 '(org-export-with-drawers (quote (not)))
 '(org-file-apps
   (quote
    (("\\.png\\'" . default)
     ("\\.jpg\\'" . default)
     (auto-mode . emacs)
     ("\\.mm\\'" . default)
     ("\\.x?html?\\'" . default)
     ("\\.pdf\\'" . default)
     ("\\.rdp\\'" . "mstsc.exe %s"))))
 '(org-global-properties (quote (("Effort_ALL" . "0:00 1:00 2:00 4:00 8:00 16:00"))))
 '(org-log-into-drawer t)
 '(org-outlook-location
   "C:/Program Files (x86)/Microsoft Office/Office14/OUTLOOK.EXE")
 '(org-pandoc-options-for-docx
   (quote
    ((reference-docx . "pandoc-reference-style-opitz.docx"))))
 '(org-plantuml-jar-path
   "C:\\ProgramData\\chocolatey\\lib\\plantuml\\tools\\plantuml.jar")
 '(org-refile-use-outline-path (quote file))
 '(org-src-fontify-natively t)
 '(org-support-shift-select t)
 '(paradox-github-token t)
 '(tidy-config-file "/cygdrive/c/Users/abellmann/emacs/spacemacs/.tidyrc")
 '(visual-line-mode nil t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((((class color) (min-colors 257)) (:foreground "#F8F8F2" :background "#272822")) (((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(company-tooltip-common ((t (:inherit company-tooltip :weight bold :underline nil))))
 '(company-tooltip-common-selection ((t (:inherit company-tooltip-selection :weight bold :underline nil))))
 '(org-agenda-clocking ((t (:inherit secondary-selection :background "PaleVioletRed2"))))
 '(org-agenda-restriction-lock ((t (:background "black"))))
 '(org-level-2 ((((class color) (min-colors 8) (background light)) (:foreground "blue"))))
 '(org-level-3 ((t (:inherit variable-pitch :foreground "cornflower blue" :weight bold :height 1.15))))
 '(org-level-4 ((t (:inherit variable-pitch :foreground "SlateGray4" :weight bold :height 1.1))))
 '(org-todo ((t (:foreground "dark violet" :weight bold))))
 '(org-warning ((t (:foreground "red" :underline nil :weight normal)))))
